### ISSUE TITLE
Design: Weather Event Notifications

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#1]
As an **inventory manager**, I need to be notified when new shipments are suggested in anticipation of a significant weather event so that I can choose whether or not I want to create the order.

**Comment by Austinauth** [comment]
@kingtraceyj We need to complete design for the Alert/Notification log.

Right now the Alert Log simply reads *1 Storm Detected* (see below).
![screen shot 2016-12-12 at 3 13 52 pm](https://cloud.githubusercontent.com/assets/6994218/21117030/c23b92a8-c07d-11e6-9735-fb5117ed5d8f.png)

The original idea of the Alert Log was to have it surface actionable notifications. For example:

![screen shot 2016-12-12 at 3 17 26 pm](https://cloud.githubusercontent.com/assets/6994218/21117142/22ca3b88-c07e-11e6-9cf9-ef7bfcb264cf.png)

Ideally, in the context of the Weather Event. The notification would tell you the: 
* Type of warning
* Affected items
* Recommended action(s)
* Ability to complete (approve/reject) recommended items)

**Comment by kingtraceyj** [comment]
we've taken out the persistent weather dialog box and replaced it with an inline warning that can be dismissed if needed. 

more details are available once weather event is selected. a user can take action within this module.

![dashboard - weather selected](https://cloud.githubusercontent.com/assets/20582179/21326576/d47c4200-c5f0-11e6-8213-6ad3edce6d4b.png)

**Comment by Austinauth** [comment]
I think the notification is solid. I think we discussed the map module would slide down vertically to make room for the notification.

Do we have any idea what the exact copy of the notification will be? Should there be a way to click the notification so it focuses on the weather event in the map?
