### ISSUE TITLE
Change JWT TTL policy

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#100]
To manage session timeouts with two different tokens, we will set both tokens (Controller-issued JWT and ERP-issued Loopback) to expire at the same time. That way they effectively need to be refreshed at the same time and will also work for Recommendations engine.

Both TTL values will be set to **1 week**.

**Comment by JakePeyser** [comment]
@l2fprod I believe Loopback API TTL is 1 week already, right?

**Comment by l2fprod** [comment]
@JakePeyser 2 weeks in loopback:
from user.js
var DEFAULT_TTL = 1209600; // 2 weeks in seconds

**Comment by JakePeyser** [comment]
Implementation in Controller changed to 2 weeks like Loopback
