### ISSUE TITLE
Document the steps on running odoo in Bluemix

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#106]
Last week, I briefly looked at odoo and how to run it in IBM Containers. This task is about documenting the howto.

related to #105

**Comment by l2fprod** [comment]
put the steps in:
https://github.com/IBM-Bluemix/logistics-wizard/wiki/Run-Odoo-in-Bluemix

**Comment by rvennam** [comment]
Looks good...worth being its own blog post if you ask me
