### ISSUE TITLE
Assess Odoo ERP

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#107]
Can Odoo be used as a replacement to the ERP simulator to support a more realistic demo scenario?

How does Odoo object model map to the ERP service model?

What is Odoo API? And how to authenticate in Odoo?

related to #105

**Comment by l2fprod** [comment]
Putting finding in https://github.com/IBM-Bluemix/logistics-wizard/wiki/Odoo-and-ERP-service

**Comment by jakepeyser** [comment]
Good overview today and succinct summary of Odoo and module capabilities. We'll put this aside for a bit now and do a deeper evaluation once we get the basic UI in place and our needs from the ERP are cleaer.
