### ISSUE TITLE
Use Postgres in place of Cloudant in ERP service

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#111]
The ERP service data is inherently relational. Using Postgres would also allow us to use transactions in loopback.

**Comment by jakepeyser** [comment]
Still need to complete #119 before closing this out

**Comment by l2fprod** [comment]
@jakepeyser: I had moved #119 to a story. It is larger than moving to PostgreSQL, it covers our full project and should be handled separately. Unfortunately I don't see a way to remove its reference it from this story.

**Comment by jakepeyser** [comment]
That is fine with me. References unfortunately can't be dropped. Even GitHub isn't perfect. Closing this out.
