### ISSUE TITLE
Test stage in the toolchain uses node v0.10 but deployed app uses node 4.4

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#112]
We should at least run the test with the latest Node version available in the toolchain.

From https://new-console.ng.bluemix.net/docs/services/DeliveryPipeline/deploy_var.html#deliverypipeline_resources,
this means 4.2.2. This can be enabled by changing the stage script and adding:
```
export PATH=/opt/IBM/node-v4.2/bin:$PATH
```

**Comment by jakepeyser** [comment]
Issue moved to [IBM-Bluemix/logistics-wizard-toolchain #1](https://github.com/IBM-Bluemix/logistics-wizard-toolchain/issues/1) via [**ZenHub**](https://www.zenhub.com/)
