### ISSUE TITLE
Validate ERP service with Postgres connector

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#114]
Run unit tests with Postgres database in Bluemix and fix any issues.

related to #111

**Comment by l2fprod** [comment]
@jakepeyser 

Got it to work after using numbers for all IDs. However this changes the Loopback API JSON and now all ID are number - Loopback could have just always use string for ids in the REST API but it is not the case (https://github.com/strongloop/loopback/issues/2046). This has side effects on the controller API that assume the IDs are string. Typical issues are like:

```
    url = Config.ERP + "Shipments/" + shipment_id
TypeError: cannot concatenate 'str' and 'int' objects
```

because now the shipment_id is a number and can't but added to a string without conversion.

I'm working on fixing the controller code.

**Comment by l2fprod** [comment]
ready for the next integration steps

**Comment by jakepeyser** [comment]
LGTM
