### ISSUE TITLE
Update toolchain template to provision a Postgres database instead of Cloudant

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#115]
May also need to have an initialization script that will create the tables in Postgres

related to #111

**Comment by l2fprod** [comment]
@jakepeyser 

I wanted to push this change:

```
-      cf create-service cloudantNoSQLDB Shared logistics-wizard-erp-db
+      cf create-service elephantsql turtle logistics-wizard-erp-db
```

but I don't have the right to do it in logistics-wizard-toolchain. Can you change the project settings?

**Comment by jakepeyser** [comment]
@l2fprod done

**Comment by l2fprod** [comment]
@jakepeyser thanks! Happy 4th July! 🍔  🍻

**Comment by l2fprod** [comment]
Database initialization done by the loopback startup code - to be moved to "one-off task" as another task.

**Comment by jakepeyser** [comment]
Works for me
