### ISSUE TITLE
Update the toolchain to test Logistics Wizard without relying on the production environment and with real external resources

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#119]
- [x] Current tests for the ERP service run with the in-memory db. It is a good start but not fully accurate given each db connector comes with its own specificities.
- [x] Tests for the logistics-wizard target the production environment.

We should have a configuration that run tests in a similar environment as the production one, with a real database.

**Comment by jakepeyser** [comment]
Controller no longer relies on prod environment - completed by #126

**Comment by rvennam** [comment]
lgtm
