### ISSUE TITLE
Make email sending a one-off worker task

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#121]
When a demo is created and an accompanying welcome email is sent, this should optimally be asynchronous. The [first attempt at this](https://github.com/IBM-Bluemix/logistics-wizard/blob/c2940fca2d7716360e25f78f09111c45e0f5c4e3/server/services/demos.py#L77-L78) unfortunately created a zombie process and thus is being replaced with a synchronous call. Once we implement a method of running one-off tasks (task #120), this should be used for sending emails.

**Comment by l2fprod** [comment]
no more email to be sent.
