### ISSUE TITLE
Consolidate Controller Unit Tests

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#125]
Consolidate the [Controller unit tests](https://github.com/IBM-Bluemix/logistics-wizard/tree/master/server/tests) into a single script so that they can be updated without having to change the invoking call.

**Comment by jakepeyser** [comment]
Converted all tests into `TestSuite` compatible classes and refactored them to share objects and optimize runtime. Created [`run_tests.py`](https://github.com/IBM-Bluemix/logistics-wizard/blob/master/server/tests/run_tests.py) as a test runner so we can now invoke the unit tests from a single script. Documentation and toolchain updated accordingly.

**Comment by l2fprod** [comment]
LGTM
