### ISSUE TITLE
Run Controller Tests in Isolation

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#126]
Enable the Controller unit tests to be run in isolation without the need to hit the production `logistics-wizard-erp` instance.

**Comment by jakepeyser** [comment]
We are now using the `module/erp` submodule to fetch the ERP app from GitHub and running it locally in the background using [nohup](http://linux.die.net/man/1/nohup). We then execute the Python unit tests as normal, this time with the `ERP_SERVICE=http://0.0.0.0:3000/api/v1/` instead of the production ERP URL.

Updated toolchain's controller pipeline TEST stage script to execute these steps: https://github.com/IBM-Bluemix/logistics-wizard-toolchain/commit/db4b9cac3fe7af790f0044f4b71ac3551c299b16

**Comment by l2fprod** [comment]
LGTM
