### ISSUE TITLE
Inventory and shipment management API

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#131]
Aim of this story is to handle the inventory updates as shipments are created and delivered.
The current Inventory model in the simulator has no business logic.

_Proposed changes_
* Remove the default Loopback generated API in order to implement custom business logic
* Introduce "reserved quantity" in product inventory at a location to avoid shipping the same product twice

_Lifecycle of a Shipment_
**To create a new shipment**
* Use POST /Shipments to create a new shipment
* Use POST /Shipments/{id}/items to add line items to a shipment
* Shipment status becomes NEW

**To approve a shipment**
* Use PUT /Shipments/{id} with a { status: "APPROVED" }
* Shipment status becomes APPROVED
* Shipment can no longer be modified
* Line items can no longer be modified
* Inventory lines for the products in the shipments are updated and quantity reserved.

**To notify of shipping in progress**
* Use PUT /Shipments/{id} to update location data with { status: "IN_TRANSIT", "estimatedTimeOfArrival": "a date", currentLocation: { an address } }
* Only if current status is APPROVED or IN_TRANSIT
* Shipment status becomes IN_TRANSIT

**To complete the delivery**
* Use PUT /Shipments/{id} with { status: "DELIVERED", currentLocation: { <an address> } }
* Only if current status is IN_TRANSIT
* Shipment status becomes DELIVERED
* Inventory lines for the products in the shipments are updated, actual stock is decreased, reserved quantity is updated.

**To cancel the shipment**
* Use DELETE /Shipments/{id}

**Comment by jakepeyser** [comment]
Some thoughts:
- I believe a `PUT /Shipments/{id}` would solve many of these issues w/o requiring dedicated methods (i.e. `.../approve`, `.../intransit`, etc.)
- I am a bit confused on your use of "quantity reserved". Is it related to the `Retailer` object where the shipment is headed or the `DistributionCenter` origin? I think stock of an item should be decreased as soon as a shipment is created and just placed back into the pool if it is rejected/modified.

**Comment by jakepeyser** [comment]
Added `test_update_invalid_status` unit test in [`test_shipments_service.py`](https://github.com/IBM-Bluemix/logistics-wizard/blob/master/server/tests/test_shipments_service.py) to make sure `ValidationExceptions` are raised when statuses are changed to an invalid value (e.g. `APPROVED` -> `NEW`)

**Comment by jakepeyser** [comment]
LGTM
