### ISSUE TITLE
Use transaction in ERP simulator to avoid corruption of data in concurrent API calls

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#135]
Aim of this story is to review the ERP simulator and use Loopback transactions whenever needed.

Typically in demo.js, shipment.js, some remote methods alter multiple tables and objects at the same time. These methods should be protected against concurrent API calls that could potentially corrupt the data - as example executing two different shipment approvals at the same time could corrupt the inventory data today.

**Comment by jakepeyser** [comment]
Issue moved to [IBM-Bluemix/logistics-wizard-erp #18](https://github.com/IBM-Bluemix/logistics-wizard-erp/issues/18) via [**ZenHub**](https://www.zenhub.com/)
