### ISSUE TITLE
Create and Publish Python Deployment Tracker Client

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#138]
We use the [cf-deployment-tracker](https://github.com/IBM-Bluemix/cf-deployment-tracker-service) to keep track of deployments of our demos and sample apps. Right now, we have several clients in different languages, but we need a Python one for the controller app.

**Comment by jakepeyser** [comment]
Created the [cf-deployment-tracker-client-python](https://github.com/IBM-Bluemix/cf-deployment-tracker-client-python)

**Comment by jakepeyser** [comment]
Published the [`cf-deployment-tracker` package on PyPi](https://pypi.python.org/pypi/cf-deployment-tracker)

**Comment by jakepeyser** [comment]
Deployment tracking added in https://github.com/IBM-Bluemix/logistics-wizard/commit/ffc8979c71329dfce3f03a6d456494642ffa90e3

**Comment by jakepeyser** [comment]
Since gunicorn is spawning multiple workers, multiple deployment events get fired to the deployment tracker. Need to eventually only fire one per deployment per app deployment. Created issue #145 to track this effort.

**Comment by rvennam** [comment]
LGTM
