### ISSUE TITLE
Service Discovery - Controller

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#139]
Implement service registry and discovery within the Python controller app

See #55

**Comment by jakepeyser** [comment]
PR #141 submitted - looking for @cphrmky feedback on:

1. I created [service-discovery.py](https://github.com/IBM-Bluemix/logistics-wizard/blob/9c1f6b613697787c58773dbd48d4d268e93d742b/server/services/service_discovery.py) to handle the SD operations. I didn't create any classes (like a ServicePublisher) as I thought it would be excessive. Does the situation warrants that sort of design?
 
2. When a service is registered, it spawns a thread to heartbeat the service at the rate of .75x the TTL value. This works well, but since there is no object created I lose control over that thread and have no way of gracefully ending [the while loop that emits the heartbeats](https://github.com/IBM-Bluemix/logistics-wizard/blob/9c1f6b613697787c58773dbd48d4d268e93d742b/server/services/service_discovery.py#L17-L20). What would be the best way to keep track of this thread so that we have a way of turning off the heartbeats? For instance, we would like to stop this thread and then deregister the service if there is an exit event for the app.

**Comment by jakepeyser** [comment]
Created Service Discovery wrapper and updated calling app/test code - https://github.com/IBM-Bluemix/logistics-wizard/pull/141/commits/db6f8f9a0ab44cc906d315338d1b2b8f563c7678

**Comment by l2fprod** [comment]
LGTM pending the comments I made in the other commits related to the "DEV" tag - I should have started my review by this issue!
