### ISSUE TITLE
Service discovery heartbeat url should not be contructed

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/logistics-wizard#143]
In def heartbeat_service(self), we are constructing the heartbeat URL, instead of using the URL returned by the registration call.

Documentation: "Important: After you register an instance, different URLs are returned. For example, the URL assigned to heartbeat is the one that you must use to renew the registration of the instance. Do not construct manually the URL based on the returned instance ID."

**Comment by jakepeyser** [comment]
Fair enough, I will update accordingly. Please use all the necessary labels when creating new issues

**Comment by rvennam** [comment]
Looks good
