### ISSUE TITLE
Set up groundwork for building UI

### ISSUE THREAD

**Issue by colbycheeze** [IBM-Bluemix/logistics-wizard#144]
As with any serious project, there comes the annoying task of setting up the initial boilerplate to get everything running.

I'm making sure we have a solid foundation to work from so I am getting our build pipeline via Webpack set up.

I'll have React, Redux, Redux-saga (for async actions), React Router with a clean folder structure and a few examples set up showing code splitting etc.
We will be going with css modules and working with React-Material-UI.

For code quality: ESLint rules via AirBnB / editor config, Tests. I'll be using AVA as the test framework, and enzyme for shallow rendering of React components in test environment. Sinon, nock, and other helper utils will be ready to go as well.

The dev environment will support Redux and React dev tools with Hot Module Reloading working.
There are a number of scripts set up which can be run in the dev environment and by prod for building, linting, testing, etc. you name it.

I'll be doing my best to document how the project works and instructions for a brand new person to get started with it as I build it out.

**Comment by colbycheeze** [comment]
- [ ] Add Redux-Saga middleware and create example usage, remove Thunk
 - [ ] Add Material-UI and use 1-2 components for examples
 - [ ] Finish updating code to airbnb eslint rules

**Comment by jakepeyser** [comment]
Additional items #161 and #167 created to track remaining work. Otherwise, branch has been merged. Nice work @colbycheeze
