### ISSUE TITLE
Document Dev Process

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#147]
Document our development process and how we manage dev/build/deploy using GitHub, Toolchain, and Bluemix

**Comment by jakepeyser** [comment]
Added a [Development Process](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Development-Process) section to the wiki, breaking down each step in our process

**Comment by l2fprod** [comment]
Great write up!

LGTM
