### ISSUE TITLE
Global Nav & Role Switcher

### ISSUE THREAD

**Issue by kingtraceyj** [IBM-Bluemix/logistics-wizard#149]
Complete UX and Visual for Global navigation & role switching

- Logo
- Persistent Git Hub link
- Role Switcher
- Clear/Restart Session
- Explore how to find session link

Story #12

**Comment by colbycheeze** [comment]
Yea I like holding context of role in the app bar. It could be easy to show the user of the app which role they are in (SCM, or RSM) by changing the color of the app bar similar to google inbox, IE:

Inbox:
![image](https://cloud.githubusercontent.com/assets/8884298/17536240/44576b7c-5e59-11e6-9d3f-6588ab2764e2.png)

Done:
![image](https://cloud.githubusercontent.com/assets/8884298/17536250/5e1a80bc-5e59-11e6-977a-d38fa00bcf75.png)

**Comment by jakepeyser** [comment]
Love it, I think that works perfectly.

> In order for us to design the Demo Settings panel we need a concrete script that calls out specific scenario triggers (weather, notifications, etc...)

The [scripts will be located here](https://ibm.box.com/s/udw65va6s67bh3l62733hgr7dluray78), it is next on my list of non-dev work items. This also begs the question on if it needs to be a "settings" menu or can just be another dropdown button to trigger specific events.

> Will the Supply Chain Manager have a location as well?

No, their role is global for the sake of the demo

> Should we surface the actual names of the Supply Chain Manager & Retail Managers?

Let's do it like you designed for now (role w/ location subtext). If we feel it's necessary, we can build in display of real names later. Right now they are like `name: Retail Store Manager (fTC72mfeR8), email: ruth.fTC72mfeR8@acme.com`, which is not very user friendly.

**Comment by Austinauth** [comment]
@jakepeyser 

> The scripts will be located here, it is next on my list of non-dev work items. This also begs the question on if it needs to be a "settings" menu or can just be another dropdown button to trigger specific events.

I think you're right. As long as the scenario triggers/settings aren't super complicated, they should probably be in a dropdown in the same vein as the *Role Switcher*.

**Comment by kingtraceyj** [comment]
global nav and role switcher comps

@LRRoberts0122 do you need redlines or do you want to start with this and then we can adjust later?

![global navigation lw](https://cloud.githubusercontent.com/assets/20582179/17632711/74b7f7e0-608f-11e6-9077-0e8cb19d71a7.png)

Type:
In the header I'm using Libre Franklin - .875em/14px Bold #FFFFFF 

Here's a quick type reference:
![lw type](https://cloud.githubusercontent.com/assets/20582179/17633479/1cd2189a-6093-11e6-90fa-ebca9ca7ea7b.png)

**Comment by LRRoberts0122** [comment]
No need for red lines. =) Will start working on the updates! =)

Also @colbycheeze I can update the typography thing in Storybook if you want? Or did you want to keep that the same? Or???

**Comment by colbycheeze** [comment]
Looks like you have 6 heading types @kingtraceyj so may as well have H1 be the 4rem size and then if most titles use h3 (which then would be the 2.5 rem type), that's likely fine.

**Comment by kingtraceyj** [comment]
sure. that sounds good. i probably won't use them but lets do it!

**Comment by colbycheeze** [comment]
Also when it comes to "red lines" what you can do is reference the type size or style you have defined (define more if you have others which are reusable)

IE: button, subheading, thin, light which is  how we will apply styles to things (as opposed to giving us the specific font weights and sizes every time)

So for now we have a few defined which we can update to use w/e reusable styles you are planning to have
```
em, .em { font-style: italic; }
strong, .strong { font-weight: 600; }
small, .small { font-size: 75% }
.light { font-weight: 300; }
.thin { font-weight: 200; }
```

So based on this typography I'd add something like 
```
.subheading {
  $base-font-size * 0.75rem;
  letter-spacing: 0.5rem;
}
```

**Comment by LRRoberts0122** [comment]
Okay, so I've been having an issue incorporating fonts for some reason. They work externally, but I think something with React or whatever is causing conflicts. I'm not 100% sure, so I'm just working around the typography issue for now, and I'll get back to it at some point. =) But I just wanted to let you guys know! @kingtraceyj

**Comment by kingtraceyj** [comment]
@LRRoberts0122 
Here's the updated hover for the role switcher. I made it a little more clear on whats selected than before with adding in a background color.

![image](https://cloud.githubusercontent.com/assets/20582179/17789964/1a66321e-655a-11e6-8639-aea80687e1ef.png)

**Comment by colbycheeze** [comment]
Issue moved to [IBM-Bluemix/logistics-wizard-webui #2](https://github.com/IBM-Bluemix/logistics-wizard-webui/issues/2) via [**ZenHub**](https://www.zenhub.com/)
