### ISSUE TITLE
Dashboard Layout

### ISSUE THREAD

**Issue by kingtraceyj** [IBM-Bluemix/logistics-wizard#150]
Complete UX & Visual for layout
- product IA
  - retail manager
  - supply chain manager
 
- Side navigation design

Story needed

**Comment by Austinauth** [comment]
@jakepeyser @rvennam

As @kingtraceyj and I start to take a deeper look at putting together a dashboard design a few questions came up.

* A couple weeks back we came across [this box note on a proposed Logistics Wizard UI](https://ibm.app.box.com/notes/72540160705), is this still valid and accurate?
* We have [personas](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Personas) and a general understanding of their tasks and needs, it seems like we need to establish an actual company with product(s) for the demo? For example, are they selling coffee products? Automotive parts? etc...
* Do you have specific modules in mind for the different persona dashboards based off of the demo scripts? We're a little unclear on what specific items need to be available to the different personas.

**Comment by jakepeyser** [comment]
@Austinauth 

> is this still valid and accurate?

Yes, those still apply, but they are not all valid for v1. Let me know if you need clarity around v1 expectations again but check the email I sent first.

> it seems like we need to establish an actual company with product(s) for the demo? For example, are they selling coffee products? Automotive parts? etc...

Yes, the company is LargeCorp and they are a big box retailer (e.g. Walmart) that sells just about anything. This makes the various scenarios (snow, heat wave, social media, etc) relevant for the company. However, the UI/UX should be pretty agnostic of the company/products. It should be easy for someone to white label the demo.

> Do you have specific modules in mind for the different persona dashboards based off of the demo scripts? We're a little unclear on what specific items need to be available to the different personas.

The views should be relatively the same for both personas. The scope of the data (global vs localized) will be the main difference, but this is mostly an implementation detail. I think we should discuss questions you have about specifics modules/details if they exist. You may have to make some assumptions for the personas and that is ok for the purpose of this demo, but refer back to the wiki descriptions when in doubt.

**Comment by Austinauth** [comment]
A brainstorming session we held yesterday ended with @jakepeyser reiterating the main requirements for the MVP:

**View Distribution Centers**
- View relevant distribution centers for persona
- View Inventory

**View Retailers**
- View relevant retailers for persona
- View shipments en-route

**View Shipments**
- View all shipments for persona
- View shipment contents
- View origin + destination

@darinduvall Long-term I think we need to have a discussion around how far we want to take this demo and how we set the context for the design playbacks we have to the greater Bluemix team. 

Based off what has been scoped to the MVP it seems like most of the demo is set to revolve around a map view featuring items like: Distribution Centers, Retail Stores, Shipments, and Stock Levels. While a map view is valuable it can be difficult to use as a primary means of keeping track of things like inventory, store locations across a large region, scenarios featuring many retail/distribution centers, and comparing data sets. 

In the future I'd like to explore how we can incorporate other modules and patterns like table and list view to detail incoming/outgoing orders. 

## Initial Low-Fidelity Dashboard Concept (Supply Manager)
*These concepts are meant not only to illustrate a potential Supply Dashboard but to raise questions regarding the appropriate amount of data/content to surface to the end-user of our demo app.*
![dashboard - supply chain copy](https://cloud.githubusercontent.com/assets/6994218/17822080/99b06740-661a-11e6-9528-6f9eba21f484.png)
The map is comprised of:
* <img width="56" alt="screen shot 2016-08-19 at 2 40 25 pm" src="https://cloud.githubusercontent.com/assets/6994218/17822137/ea88cc16-661a-11e6-8170-2ceecdcb797d.png"> - **Retail Stores**
* <img width="62" alt="screen shot 2016-08-19 at 2 42 35 pm" src="https://cloud.githubusercontent.com/assets/6994218/17822181/33070778-661b-11e6-8dc4-3e6caaa9ea5c.png"> - **Distribution Centers**
* <img width="64" alt="screen shot 2016-08-19 at 2 43 31 pm" src="https://cloud.githubusercontent.com/assets/6994218/17822202/54fff984-661b-11e6-9d32-87ee69da3569.png"> - **Shipment/Order**
* <img width="45" alt="screen shot 2016-08-19 at 2 44 05 pm" src="https://cloud.githubusercontent.com/assets/6994218/17822210/691504b4-661b-11e6-85a9-1f21f15cfe2f.png"> - **Destination**

Visually we can explore the best way to convey these items through iconography and color.

## Checking Status
Selecting a map item would reveal relevant content to the selected item.
![dashboard - supply chain copy-2](https://cloud.githubusercontent.com/assets/6994218/17822249/a60900aa-661b-11e6-8962-5d46adcf821b.png)
![dashboard - supply chain copy-3](https://cloud.githubusercontent.com/assets/6994218/17822265/cc02e1b8-661b-11e6-800c-72acb3b0665c.png)
![dashboard - supply chain copy-4](https://cloud.githubusercontent.com/assets/6994218/17822316/1260f942-661c-11e6-838d-99c6807e07df.png)

**Comment by colbycheeze** [comment]
Are there plans for something to be inside that bar on the left?

**Comment by colbycheeze** [comment]
Issue moved to [IBM-Bluemix/logistics-wizard-webui #6](https://github.com/IBM-Bluemix/logistics-wizard-webui/issues/6) via [**ZenHub**](https://www.zenhub.com/)
