### ISSUE TITLE
Design SAP Integration

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#151]
We need to finalize the architecture of the integration with the SAP system. This needs to be scoped out on Mural.ly and once completed, individually tasked out here.

**Comment by jakepeyser** [comment]
Bernd has provided us with a x86 Ubuntu VM for hosting the Secure Gateway. Ram is giving the setup a go.

**Comment by rvennam** [comment]
Have Secure Gateway set up on VM. Chris is looking into the layer/gateway we will use to communicate with SAP

**Comment by shenybluemix** [comment]
Two options:  - SOA Manager
                        - JCO

Doing some research on which one is the easiest one. The bottom line is to use JCO
