### ISSUE TITLE
Create architecture diagram

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#153]
Create an architecture diagram for v1 of the app

Story #73

**Comment by jakepeyser** [comment]
[Box folder with source files](https://ibm.box.com/s/x6yr5r08p0ew1povwf2wdtjgx7i6v2uh)

First draft:
![architecture_diagram_v1](https://ibm.box.com/shared/static/lw2if5htihlbjtghoqo6jg8sgowivccz.png)

Also [posted on the wiki home page](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Home)

**Comment by uwefassnacht** [comment]
Looks quite good. I think the only comments from me would be:

**Comment by jakepeyser** [comment]
- [ ] Bluemix boundary
- [ ] Service labels
- [ ] 90 degree arrows

**Comment by jakepeyser** [comment]
@uwefassnacht new version good?

**Comment by uwefassnacht** [comment]
Yes. Love it!

**Comment by jakepeyser** [comment]
Posted new PNG w/ transparent background
