### ISSUE TITLE
Draft explanatory copy for landing pages

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#154]
Concisely explain the purpose of the app, the user personas, and what is intended to be shown in v1

Story #73

**Comment by jakepeyser** [comment]
**Tagline**: Let your global supply chain do the THINKing, so you don't have to.

**Short Description**: A cognitive logistics solution that analyzes real-time data, provides intelligent recommendations, and presents your employees with a beautiful monitoring dashboard to help lead your supply chain management system into the future.

**Tech Feature Sections**
_**Hybrid**_ - Connect to your existing on-premises ERP system and give your data a makeover.
_**Cognitive**_ - Ingesting data sources like weather and social media in real-time enables your supply chain managers with instantaneous resource planning from Watson.
_**Hands-Off**_ - Monitoring, alerts, automatic updates, and more come standard with Cloud Foundry and the IBM Open Toolchain.

This plus the architecture diagram should be enough for v1. We should also include a link to [the wiki](https://github.com/ibm-bluemix/logistics-wizard/wiki) as the _user manual_ of the application.

**Comment by jakepeyser** [comment]
@Austinauth and team: please review

**Comment by l2fprod** [comment]
"Let your global supply chain do the THINKing, so you don't have to."
-> the supply chain gets smarter but you still own the decision based on automated recommendations. The tagline makes me think that I don't have anything to do.

"standard with Cloud Foundry " -> with IBM Bluemix

**Comment by jakepeyser** [comment]
> the supply chain gets smarter but you still own the decision based on automated recommendations. The tagline makes me think that I don't have anything to do.

I still think our demo does quite a bit of "thinking", I mean it is a sister word to "cognition". I like the tagline because it is short, relevant, and had branding power but I'm open to changes if people think it is misleading.

> "standard with Cloud Foundry " -> with IBM Bluemix

Done

**Comment by Austinauth** [comment]
@jakepeyser Sorry for the delayed response - just saw this.

Unfortunately I'm not as much of a copywriter as I'd like to be. In this case, the copy works and seems appropriate.

From what I've seen, @kingtraceyj has been incorporating your copy into her mocks of the landing page without issue.
