### ISSUE TITLE
Add env tag to service registry record and use during service lookup

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#159]
We need to make sure we are looking for the correct service instance (i.e. `DEV`, `PROD`, etc) when we lookup services in the registry. Therefore, when registering a service we need to add the env tag from the `LOGISTICS_WIZARD_ENV` env var that is available in both the pipeline and Bluemix environments.

This task is for adding the tag when registering the Controller service and searching for the correctly tagged service during service lookup.

**Comment by rvennam** [comment]
LGTM
