### ISSUE TITLE
Figure out how to merge Python controller and front-end build tests

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#161]
The React/Redux code has its own set of unit tests that should be ruin during the build. Since it is in the same repo as the controller code, we need to figure out how to run both these and the server-side tests in the same build. We then need to determine how to combine their coverage files so that it is all sent to coveralls.io

**Comment by l2fprod** [comment]
this is no longer needed. UI and backend are separate apps with their own pipeline.
