### ISSUE TITLE
Create FAQ of common issues in wiki

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#165]
This is a large app and as such, it is likely that users will run into various issues while setting it up and playing with the demo. We should collect common issues into an FAQ in the wiki and link to places (i.e. wiki pages, READMEs, etc) for more info. [#24](https://github.com/IBM-Bluemix/logistics-wizard-erp/issues/24) is a good example of an entry in the FAQ

**Comment by jakepeyser** [comment]
Added [FAQ page](https://github.com/IBM-Bluemix/logistics-wizard/wiki/FAQ) to the wiki

**Comment by rvennam** [comment]
LGTM
