### ISSUE TITLE
Landing Page Design

### ISSUE THREAD

**Issue by Austinauth** [IBM-Bluemix/logistics-wizard#166]
Complete UX & Visual for Logistics Wizard landing page

* Content incoming from @jakepeyser 
* Basic description of the app
* Architecture diagram
* IT components & services meant for showcase
* Source code link (Global header?)
* Entry flow trigger

Reference step 1 of the [original experience diagram](https://ibm.app.box.com/notes/75279614890?view_comment=109205265)

**Comment by Austinauth** [comment]
@kingtraceyj Did you need me to mock anything up for this?

**Comment by kingtraceyj** [comment]
@Austinauth i think what ben did was a great start. i'll use that for the basis. we'll just need the content  to fully design it.

**Comment by kingtraceyj** [comment]
Attached is the comp of the landing page.

There are a few calls to action.

- github source code link at the top
- a button to try it live (is this possible or does anyone who uses it need to fork it and use it?)
- a link to the wiki -- this needs some copy edits. should we call out that it's linking to git hub? jake suggested we could call it user manual or something along those lines.

any feedback would be appreciated!


![lw_landingpage](https://cloud.githubusercontent.com/assets/20582179/17872052/eefc93a2-6883-11e6-8ffe-e321b1a2b671.png)

**Comment by colbycheeze** [comment]
Issue moved to [IBM-Bluemix/logistics-wizard-webui #3](https://github.com/IBM-Bluemix/logistics-wizard-webui/issues/3) via [**ZenHub**](https://www.zenhub.com/)
