### ISSUE TITLE
Update front end docs

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#167]
Update all documentation and files to reflect this specific project and make sure there are no leftover artifacts from the boilerplate code.

fyi: @colbycheeze @LRRoberts0122

**Comment by jakepeyser** [comment]
- [`package.json` author](https://github.com/IBM-Bluemix/logistics-wizard/pull/160/files/8b345b010a6b6096b86c2a41dbd27a92f3b0f36b..a373c833d161008ed2fc81f711079ad04b60ad73#r74586128)
- [boilerplate README badges](https://github.com/IBM-Bluemix/logistics-wizard/pull/160/files/4bba320b03add5c240068aeda29453c28f459b77#r74582787)
- etc

**Comment by jakepeyser** [comment]
Place non-app contextual info inside the wiki

**Comment by colbycheeze** [comment]
Issue moved to [IBM-Bluemix/logistics-wizard-webui #9](https://github.com/IBM-Bluemix/logistics-wizard-webui/issues/9) via [**ZenHub**](https://www.zenhub.com/)
