### ISSUE TITLE
Flesh out Recommendations Service Use Case and Details

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#17]
In Scope: 
- Centralized the Recommendation Services (a hub)which will take input from different other services/APIs/datas 
and give recommendations based.   
- The services is robust meaning that if one of the inputs services/APIs are down. The recommendation service is still up and running
-  The recommendations are actionable and programmatically consumable by other downstream services

Not in Scope:
- Not building another Watson (but powered by Watson) 
- No deep learning (but powered by deep learning)
- Not a general recommendation service?

**Comment by shenybluemix** [comment]
- Centralized the Recommendation Services which will take input from different other services/APIs/datas 
and give recommendations based.   
- The services is robust meaning that if one of the inputs services/APIs are down. The recommendation service is still up and running
-  The recommendations are actionable and programmatically consumable by other downstream services
