### ISSUE TITLE
Set up muitheme for global colors etc

### ISSUE THREAD

**Issue by colbycheeze** [IBM-Bluemix/logistics-wizard#171]
Global theme colors etc will be set up in muitheme to pass down to all material-ui components.
ref: #92 

docs: http://www.material-ui.com/#/customization/themes

**Comment by colbycheeze** [comment]
We can pair on this if you like, or I can at least set up the groundwork when you are ready to work on styling theme related stuff @LRRoberts0122.

**Comment by LRRoberts0122** [comment]
Let's pair! =)
