### ISSUE TITLE
Move UI to a separate application

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/logistics-wizard#189]
This might be controversial, but I've given this a lot of thought, research and discussed with Colby. 

1) Our UI needs to be transpiled/packaged/built/compiled and we use npm and lots of dependencies (340MB currently) to do that. If we make this part of the build, before a push to CloudFoundry, we're pushing a large package, which will be slow and likely timeout.  

2) If you make the dependency download part of the python start script (setup.py), then we're expecting npm to be there or bring it in, and also wait until it builds. 

3) Having the UI and controller together actually makes it harder for a developer to get started. Why have the dev set up python env when they are only interested in seeing how the UI works? And vice-versa. Having node to run UI locally, and python when in production is just confusing and make it not a good sample. 

4) MICROSERVICES! 

Lets make the UI a separate application, with its own repo.

**Comment by colbycheeze** [comment]
Thanks for bringing this up, I kind of wanted to set it up this way from the beginning.
It will still be easy to have deploy to Bluemix functionality for each service on it's own TBH. The people actually using that feature may only be interested in one piece of the puzzle anyhow as you mentioned.

**Comment by l2fprod** [comment]
LGTM
and the updated pipeline uses this now.
