### ISSUE TITLE
Move controller code in its own GitHub repo

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#197]
Follow up to https://github.com/IBM-Bluemix/logistics-wizard-webui/issues/17

Move the controller code into its own GitHub repo and keep logistics-wizard as the main repo containing documentation on the project (wiki) and a README linking together all the components of the demo (erp, recommendation, webui, controller, etc).

- logistics-wizard (mainly documentation)
 - logistics-wizard-erp -> ERP service simulator, deployed at logistics-wizard-erp.mybluemix.net
 - logistics-wizard-webui -> UI built with React, deployed at logistics-wizard.mybluemix.net
 - logistics-wizard-controller -> API for the UI, deployed at logistics-wizard-controller.mybluemix.net or logistics-wizard.mybluemix.net/api/v1 to ease the integration with the UI
 - (and later the logistics-wizard-recommendation service would follow the same path as the ERP)

**Comment by rvennam** [comment]
lgtm
