### ISSUE TITLE
Update main architecture diagram

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/logistics-wizard#199]
https://ibm.ent.box.com/files/0/f/9344686826/Architecture_Diagram

**Comment by rvennam** [comment]
Created updated pdf, key and png files. Please review @l2fprod

**Comment by l2fprod** [comment]
@rvennam 

the .js on the web ui makes it look like it is a Node.JS backend, although today it is plain static - that's ok as we might need to put a simple backend to implement the service discovery lookup anyway.

do we really want the SAP logo here? We could leave this as on-prem ERP.

the database near the controller should be removed - it does not exist.

**Comment by rvennam** [comment]
Removed SAP logo and extra db.
