### ISSUE TITLE
Design: Weather-Based Event/Recommendations

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#2]
As a **supply chain manager**, I want my logistics system to analyze weather data and historical purchasing data so that it can suggest additional shipments to increase sales.

**Comment by rvennam** [comment]
For this sprint, we will have the controller/recommendation system generate shipment suggestions if weather anomaly is detected. 

@Austinauth @kingtraceyj We will need designs to display additional shipment suggestions.

**Comment by Austinauth** [comment]
@rvennam @kingtraceyj Based on our discussions last week we concluded the first iteration of the weather recommendation engine would:

* Display the type of weather warning
* Display the severity of the warning
* Indicate potential shortages
* Suggest sending additional supplies to affected locations

Here's a quick first pass at a potential design for the weather warning.

![screen shot 2016-12-12 at 3 04 06 pm](https://cloud.githubusercontent.com/assets/6994218/21116719/42abcd56-c07c-11e6-8e1f-16a2a6e2345d.png)

**Comment by kingtraceyj** [comment]
**updated comps for weather module**

![dashboard - weather selected](https://cloud.githubusercontent.com/assets/20582179/21326032/9613f5e6-c5ee-11e6-951f-3334243c861d.png)

**Comment by Austinauth** [comment]
@rvennam Will there always be a recommended action? Wondering if the Weather module will feel empty without any recommendations.
