### ISSUE TITLE
Review insurance demo in light of the logistics-wizard toolchain and how to map the two demo scripts

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#200]

**Comment by l2fprod** [comment]
@uwefassnacht @rvennam 

I need your review of the script in the private box folder.

**Comment by uwefassnacht** [comment]
> I need your review of the script in the private box folder.

Added it to my (growing) set of todos.

**Comment by rvennam** [comment]
Reviewed and made changes to OPENTOOLCHAIN-INTRO-SCENARIO

**Comment by uwefassnacht** [comment]
Reviewed and made my changes as well. We now need a GHE repo to host it. Box folders suck for version control and collaboration. 👎

**Comment by rvennam** [comment]
@l2fprod moved it to: https://github.ibm.com/Bluemix/developer-productivity/blob/master/demos/logistics-wizard/scripts/OPENTOOLCHAIN-INTRO-SCENARIO.md

**Comment by rvennam** [comment]
To prove your point, looks like my edits got lost somewhere :\
