### ISSUE TITLE
Service Discovery and Service Proxy demo script

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/logistics-wizard#205]
Using the LW microservices, create a demo that highlights the Service Discovery and Service Proxy services and the benefits of using them.
- Basic registration and listing of microservices
- Monitoring microservice performance
- Testing microservice resiliency
- Simulate unstable network conditions
- Simulate failures
- A/B testing and traffic redirection

**Comment by rvennam** [comment]
This needs to use the Amalgam8 project.

**Comment by l2fprod** [comment]
@rvennam looking at https://console.ng.bluemix.net/docs/containers/amalgam8/a8_solution_bluemix.html#a8_solution_bluemix it is quite a few commands to execute to get amalgam8 deployed. We should look into scripting all this as part of a toolchain script - given we have access to containers in the toolchain it would be great if all this gets automated.
