### ISSUE TITLE
Unclear UX when either selecting an existing demo or creating a new one

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/logistics-wizard#219]
I found this screen very confusing. As a casual user, I don't know what a "GUID" is. When would I join a demo? When would I create a new one?

![screenshot_2114](https://cloud.githubusercontent.com/assets/7142658/20842587/50f4a0ca-b8b8-11e6-8d75-8c7d51fd98e8.jpg)

I think we need more wording here to explain what the choices are. Also somehow make it visually clearer that there is a choice to be made. Maybe 2 separate buttons to continue?

**Comment by rvennam** [comment]
we recently got rid of this screen. dev is updated, prod should be updated shortly
