### ISSUE TITLE
Use mapbox vs. google maps

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/logistics-wizard#220]
Why aren't we using mapbox (featured in the Bluemix catalog: https://console.ng.bluemix.net/catalog/services/mapbox-maps) vs. google maps? 

Just like google, It has a free tier.

**Comment by l2fprod** [comment]
@uwefassnacht 

from https://console.ng.bluemix.net/catalog/services/Mapbox%20Maps it seems you have to first register a mapbox account on their website to use it. This will prevent us from automating the deployment if we pick this map provider.

**Comment by uwefassnacht** [comment]
True. I'll add that as a feedback item. Once that changes, let's re-evaluate.
