### ISSUE TITLE
Can't select anything on the map to see weather info for it

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/logistics-wizard#221]
Can't select a location or an ongoing shipment to show:
- the current weather,
- the forecast,
- weather alerts for the location

The map doesn't seem to be "clickable" .. I only get the "hand" icon that allows me to move the map. 

I can "mouse over" shipments (and get shipment No. and TOA), but can't select them either to get weather info.

**Comment by rvennam** [comment]
prod and dev are now synched. Could you try again?
