### ISSUE TITLE
Logistics Wizard n00b experience

### ISSUE THREAD

**Issue by cphrmky** [IBM-Bluemix/logistics-wizard#233]
Capture and document user experience of a programmer/developer with no prior exposure to the LW during first encounter with it.

Review items:

* How current, accurate, clear or confusing is the README and other documentation.
* Try to find and open tickets for any bugs that present when using LW exactly as documented.
* Cross platform bugs. (OS X, Linux, etc)
* Document any obvious pain points

**Comment by l2fprod** [comment]
@cphrmky a useful page to get the app running locally https://github.com/IBM-Bluemix/logistics-wizard/wiki/Quick-Start - all but the OpenWhisk actions.

**Comment by l2fprod** [comment]
reopen if needed
