### ISSUE TITLE
Design: Current weather - shipment event.

### ISSUE THREAD

**Issue by Austinauth** [IBM-Bluemix/logistics-wizard#236]
Selecting an in-progress shipment on the map should should show the current weather for that area.

**Comment by kingtraceyj** [comment]
This is what we currently have for selected shipment.

![dashboard - shipment selected](https://cloud.githubusercontent.com/assets/20582179/21776885/4628ab4c-d662-11e6-8dce-a5a070305681.png)

**Comment by kingtraceyj** [comment]
@Austinauth do you think there's room to add weather? or should we take info out?

**Comment by Austinauth** [comment]
> @Austinauth do you think there's room to add weather? or should we take info out?

@kingtraceyj Summarizing our in-person convo just so we have it captured in the issue.

All we need is to show the _Current Weather_ on the shipment event card. We should have enough space to keep both the existing attributes present as well as add the _Current Weather_. 👍 
We dec

**Comment by kingtraceyj** [comment]
updated with current weather for shipment

![dashboard - shipment selected](https://cloud.githubusercontent.com/assets/20582179/21822709/f7b2b200-d73d-11e6-9289-ae872fe75a6f.png)
