### ISSUE TITLE
Design: Weather loading indicator

### ISSUE THREAD

**Issue by Austinauth** [IBM-Bluemix/logistics-wizard#237]
We need to style the weather loading indicator to fit within the current visual guidelines.

## Current Implementation
![screen shot 2017-01-09 at 11 14 42 am 2](https://cloud.githubusercontent.com/assets/6994218/21775793/1b85968e-d65d-11e6-8db1-aea8b6816193.png)

**Comment by kingtraceyj** [comment]
**Loading Indicator**

Use IBM design language spinner. can be found on bluemix design system guide: http://carbondesignsystem.com/components/loading.html#foundation

Color: #0C7483
Size: 24px X 24px

![dashboard - retailer selected loading](https://cloud.githubusercontent.com/assets/20582179/21816820/1813d6bc-d727-11e6-9563-12700207d991.png)

**Comment by Austinauth** [comment]
Brian to implement when he joins.

**Comment by l2fprod** [comment]
done - we already had it with LoadingProgress component using the Material Circular Progress.
http://www.material-ui.com/#/components/circular-progress
