### ISSUE TITLE
Overlapping DC and Shipment at Albany, New York

### ISSUE THREAD

**Issue by rvennam** [IBM-Bluemix/logistics-wizard#243]

**Comment by l2fprod** [comment]
changing the coordinates:

![image](https://cloud.githubusercontent.com/assets/12746550/23069228/f05f7bda-f526-11e6-86fa-ca52e2d92383.png)

and then when you zoom in:

![image](https://cloud.githubusercontent.com/assets/12746550/23069249/019e0f74-f527-11e6-9393-2224a38fd201.png)


obviously this applies only to new demos. so logout and you'll need to log in to view the change
