### ISSUE TITLE
UI Changes needed for the Availability and monitoring Synthetic Script

### ISSUE THREAD

**Issue by Twanawebtech** [IBM-Bluemix/logistics-wizard#245]
Changes needed for the Availability and monitoring Synthetic script.

1) Remove the session from the URL, this is so the Synthetic script will work properly.
2) Add ID's to shipment, Retail Location, and the Simulate Storm button.

<img width="1182" alt="screen shot 2017-02-20 at 15 15 34" src="https://cloud.githubusercontent.com/assets/12715466/23130742/82018bdc-f77f-11e6-92fe-096caf670480.png">

**Comment by l2fprod** [comment]
@Twanawebtech 

can you describe the test script in user actions such as:

1. Click on "View Logistics Wizard in action"
2. Verify the number of active shipment is X
3. Click on Simulate Storm
etc.

so that we understand what UI elements you want to retrieve.

**Comment by Twanawebtech** [comment]
The test case will simulate a user doing the following:
* the user opens the Logistics Wizard site,
* clicks on the "View Logistics Wizard" button,
* clicks on the truck icon to get shipment details,
* click on the retail location icon to get location details,
* click on the weather storm button get the weather information, the weather functionality is done using an OpenWhisk action, so this will also test the OpenWhisk action.

```
  <tr>
  	<td>open</td>
  	<!-- Open the Logistics Wizard site -->
  	<td>http://<Your-App-WebUI-URL>.mybluemix.net</td>
  </tr>

  <tr>
  	<!-- Click on the "View Logistics Wizard" button to go into the dashboard -->
  	<td>click</td>
  	<td>id=viewInActionButton</td>
  </tr>

  <!-- Click on the "shipment" icon -->
  <tr>
  	<td>click</td>
  	<td>id=shipment</td>
  </tr>

  <!-- Click on the "Retail Location" icon -->
  <tr>
  	<td>click</td>
  	<td>id=retailLocation</td>
  </tr>

  <!-- Click on the "Weather Storm" button -->
  <tr>
  	<td>click</td>
  	<td>id=weatherStorm</td>
  </tr>
```

**Comment by l2fprod** [comment]
@Twanawebtech changes committed to "dev" branch. You should have all the IDs you need.

In the steps you are listing, please add one clicking on the account menu on the top right and then on "End Session". This will clean up the demo created by the test.

**Comment by Twanawebtech** [comment]
Reopening this issue.

The monitoring service test using selenium IDE still failing on this button, after a very long wait from the monitoring team, it seems that the selenium IDE is not supporting touch events. 

We need to change the "VIEW LOGISTICS WIZARD IN ACTION" button to a click event in order to work.

**Comment by l2fprod** [comment]
@Twanawebtech 

The events are Click, not Touch.

![image](https://cloud.githubusercontent.com/assets/12746550/24461616/f58ae384-14a1-11e7-9423-5d74a6bdbb82.png)

To verify, in Chrome console, under Sources, set a breakpoint on mouse/click. It will break when you click on the button. If you set a breakpoint on touch, nothing happens.

**Comment by Twanawebtech** [comment]
Well that click event is not working on the Monitoring test, see comment from the Monitoring team. 

The script failed at the step when tried to click the button of "VIEW LOGISTICS WIZARD IN ACTION", the root cause is that there is no clicking event for this button defined in this page, it is a touch event instead, and selenium webdriver doesn't support it by now, and as a workaround, you can replace the command clickAndWait with open like below:

**Comment by l2fprod** [comment]
@Twanawebtech 

I can run the test successfully in Selenium IDE with Firefox.

![image](https://cloud.githubusercontent.com/assets/12746550/24462169/9b061198-14a3-11e7-8bf2-d8583e1f7f64.png)

**Comment by Twanawebtech** [comment]
@l2fprod yes, correct it works on FireFox Selenium IDE  but the issue is with Availability Monitoring driver, they don't have support for touch buttons. You seen above comments from them.

**Comment by Twanawebtech** [comment]
Closing this for now, if needed then we will reopen.
