### ISSUE TITLE
Design: Generate Weather Event

### ISSUE THREAD

**Issue by blumareks** [IBM-Bluemix/logistics-wizard#26]
The cognitive service would pull information from Weather channel (or is subscribed to weather events) and generates the event that could become originator of the "Auto-Create Shipment" event

**Comment by uwefassnacht** [comment]
In addition to actual weather data, we also need the ability to "create" a weather event (e.g. a snow storm) for the demo. Ideally by clicking on a map location and then on "create snow storm"

**Comment by jakepeyser** [comment]
Not aligned with currently scoped work -> closing

**Comment by rvennam** [comment]
Bringing this task back into scope. In the current sprint, we would want the controller to handle the generation of a weather event triggered by an action in the UI. 

@Austinauth @kingtraceyj : Please use this as a parent task to provide design and visuals.

**Comment by Austinauth** [comment]
The *Generate Weather* button should manifest itself in the bottom right section of map (see image below).

![screen shot 2016-12-12 at 2 53 31 pm](https://cloud.githubusercontent.com/assets/6994218/21116443/36922782-c07b-11e6-8b52-78cc6cc898e2.png)

@kingtraceyj is working on the Hifi visuals for this component.

**Comment by kingtraceyj** [comment]
updated selected storm

![dashboard - weather selected](https://cloud.githubusercontent.com/assets/20582179/21328924/c083c420-c5fb-11e6-86cb-3466ea93e7cc.png)

**Comment by Austinauth** [comment]
@kingtraceyj Looks good! Thank you Tracey!
