### ISSUE TITLE
Question: What is the security model for the controller and erp cloud foundry apps?  

### ISSUE THREAD

**Issue by snowch** [IBM-Bluemix/logistics-wizard#264]
The controller and ERP cloud foundry apps are internal (not publicly facing).  How are the apis for these apps protected so that they are only accessible by the webUI?

**Comment by l2fprod** [comment]
- The controller is a proxy to the ERP API.
- The web UI goes through the controller to authenticate with the ERP API.
- Internally, the ERP API uses Loopback AccessToken to protect API calls. Tokens are issued for the authenticated users.
- The web UI keeps the access token after authentication and passes it to all further calls to the controller.

In this sample, when you deploy with Cloud Foundry, the controller and the ERP are publicly facing.
When you deploy in Kubernetes, only the controller is publicly facing.

**Comment by snowch** [comment]
Thanks, useful to know.  Would be good to add this to the README.
