### ISSUE TITLE
Controller-UI Interface

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#32]
Determine the interface between the UI and the controller service

**Story** #15

**Comment by JakePeyser** [comment]
@benrondeau can you review the [API spec defined here](http://editor.swagger.io/#/?import=https://raw.githubusercontent.com/IBM-Bluemix/logistics-wizard/implement_user_auth/swagger.yaml) and let me know if that will handle the requests you need from the front end? We can always add options to lessen the size of the returned payload (e.g. query param to not include inventory for returned distribution centers)

**Comment by benrondeau** [comment]
@JakePeyser Looks fine currently, but hard to say at this point exactly what will be needed front-end vs. server side. I assume some rendering will be done on both ends but this has not been flushed out. Until we have a solidified user flow and UI templates can a verdict be given. So yes, looks good for now.

**Comment by JakePeyser** [comment]
We just need a starting point @benrondeau, so that's ok. I don't think we are working with the amount of data to justify server-side rendering, but I am open to discussing that. Is there a particular framework you are thinking of using?

**Comment by benrondeau** [comment]
@JakePeyser I was just think about what technical framework will be best for this app on the front-end. Where do you think this should be documented?

**Comment by JakePeyser** [comment]
Up to you. I would do one of the following:
- create a new issue `Decide on UI framework` and have discussion in comments
- create a wiki page to document the potential frameworks and pros/cons for them

I think issues are better for having a conversation, but it should end up in the wiki regardless. A blog post about the framework we went with and why would be great too! but that would come later...

**Comment by benrondeau** [comment]
Sounds good. I will create that task.

**Comment by benrondeau** [comment]
Task for Decide on UI framework created -> #65
