### ISSUE TITLE
Document the deployment options for the ERP simulator

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#33]
related to #16 

* Deploy the ERP simulator and connect it directly to the rest of the demo - as if everything was running in public https://github.com/IBM-Bluemix/logistics-wizard-erp/blob/master/README-BASIC.md
* Deploy ERP simulator behind a secure gateway
* Deploy ERP simulator on-prem behind a secure gateway

**Comment by JakePeyser** [comment]
This issue was moved to IBM-Bluemix/logistics-wizard-erp#7
