### ISSUE TITLE
Technical Collateral for UI

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#37]
Plan out the content items that would be useful to developers/CIOs/etc for the UI. Ensure they all tie back to the value of the service and why Bluemix is being used.

Also, compile and send @jakepeyser examples you would like the digital agency to use as reference points. For example, this [Natural Language Classifier graphic video](https://www.youtube.com/watch?v=h1ZiUIvYdD8)

Story #21

**Comment by benrondeau** [comment]
**UI Content for Personas**

Supply Chain Manager

- Maps of where his shipments are world wide
- Alert/warning center indicating bad weather, truck breakdown, etc.
- Status of shipments (likely in a table form)
- Recommended actions for him to take
- Ability to adjust shipments to respond to situations (bad weather, etc.) 

Retail Store Manager

- Stock levels for her current store
- Review, adjust shipments her store is expecting
- Any alerts related to her store's shipments

I could easily list 100 more UI items but I am afraid that the UI will just become bloated and dilute the overall product. I need to speak with people who actually work in this industry to better understand what they want and need to do their job (a.k.a. more persona research).

**Digital Agency Request**

While I believe it is too early in the process to send Digital Agency firm items to deliver, this is what comes to mind:

- Logo for app
- Architecture diagram
- Video like this that explains the value of our app - just like the [Watson Natural Language Classifier](https://www.youtube.com/watch?v=h1ZiUIvYdD8)
- Introductions we can put at the beginning of our how-to videos, similar to what we already have for generic Bluemix intros

More will come as the app develops further...

**Comment by JakePeyser** [comment]
@benrondeau that `UI Content` is good, but this issue is not the right place for it...I believe that belongs somewhere in the wiki

**Comment by benrondeau** [comment]
@JakePeyser Okay - wasn't sure where to put this. You want to move it to the wiki and link it to this?

**Comment by JakePeyser** [comment]
please do
