### ISSUE TITLE
Technical Collateral for Recommendations Service

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#38]
Plan out the content items that would be useful to developers/CIOs/etc for the recommendations component. Ensure they all tie back to the value of the service and why Bluemix is being used.

Also, compile and send @jakepeyser examples you would like the digital agency to use as reference points. For example, this [Natural Language Classifier graphic video](https://www.youtube.com/watch?v=h1ZiUIvYdD8)

Story #17

**Comment by shenybluemix** [comment]
[IBM Watson on Weather](https://www.youtube.com/watch?v=6VMVzVYibyQ)
