### ISSUE TITLE
Technical Collateral for Weather Service

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#39]
Plan out the content items that would be useful to developers/CIOs/etc for the weather component. Ensure they all tie back to the value of the service and why Bluemix is being used.

Also, compile and send @jakepeyser examples you would like the digital agency to use as reference points. For example, this [Natural Language Classifier graphic video](https://www.youtube.com/watch?v=h1ZiUIvYdD8)

[Needs a parent story]

**Comment by blumareks** [comment]
https://github.com/IBM-Bluemix/logistics-wizard/wiki/Technical-Collateral-for-Weather-Service

**Comment by JakePeyser** [comment]
@blumareks can you please transfer that to the general [Technical Collateral doc](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Technical-Collateral)? I don't want to scatter resources ideas

However, I like the concept of splitting them up by what service goes with what content. Haven't had time  to organize it like that, would appreciate you taking a stab at it!

**Comment by blumareks** [comment]
transferred , and promoted the indent style to distinguish different microservices in the collateral :-) Let me know in the different request than #39 how you want to have it formatted / organized. Closing #39
