### ISSUE TITLE
Add link to github repo on web app

### ISSUE THREAD

**Issue by uwefassnacht** [IBM-Bluemix/logistics-wizard#42]
Need to have a way to quickly find the repo when viewing the live demo app

**Comment by JakePeyser** [comment]
Yes, this is one of the demo guidelines. @benrondeau when do you think we can import these into here?

**Comment by benrondeau** [comment]
@JakePeyser By end of week. My app just works with Github Enterprise currently, so need to make some changes for the public API.

**Comment by uwefassnacht** [comment]
Closed by mistake. Would be great if Zenhub would have an "undo" button ;-)

**Comment by JakePeyser** [comment]
Covered by Guideline #86
