### ISSUE TITLE
Complete personas for demo

### ISSUE THREAD

**Issue by benrondeau** [IBM-Bluemix/logistics-wizard#45]
Personas found [here](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Labels) need to be completed. The experience we create with this application will be based on the personas' needs

Story #21

**Comment by benrondeau** [comment]
@JakePeyser Hope we can work on this when you are back in office next week

**Comment by uwefassnacht** [comment]
I've put my thoughts here: https://github.com/IBM-Bluemix/logistics-wizard/wiki/Personas

I think we need to be very focussed with personas. Past demos had too many of them. To start with, I'd go with only the two I put into the Wiki.

**Comment by JakePeyser** [comment]
@benrondeau I added the actions I see personas taking with the ERP system last night

**Comment by benrondeau** [comment]
@JakePeyser and @uwefassnacht Thanks for your additions!!

**Comment by JakePeyser** [comment]
@benrondeau based on our conversations last week, please update [the personas](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Personas) accordingly

**Comment by benrondeau** [comment]
Setup an interview for this evening with someone who has been in both persona roles to verify my assumptions on our personas. Will document accordingly.

**Comment by benrondeau** [comment]
@JakePeyser and @uwefassnacht: I have updated the [Supply Chain Manager persona](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Personas) based on a conversation I had today with one. Please review and let me know your thoughts.

I will update the Store Manager persona once I get your thoughts back. Thanks

**Comment by JakePeyser** [comment]
Nice updates, the persona is much richer now. Overall, LGTM. The introduction of vendors into the demo and accompanying schema might complicate things more than the scope of this demo accounts for, tho. Do you think they are necessary to paint a realistic picture? I personally think other aspects of the story are compelling enough.
(btw @uwefassnacht is on PTO this week so may not respond until next week)

**Comment by benrondeau** [comment]
Updated Retail Store Manager Persona. Issue now ready for review.

**Comment by JakePeyser** [comment]
These are great, the only thing I think adds unnecessary complexity are the vendors. If we don't worry about where the goods come from, we only have to worry about one junction point (distribution -> retail), instead of (vendor -> distribution -> retailer)

**Comment by benrondeau** [comment]
Okay. When I interviewed an SME, they stressed this as important. But if it is a lot of effort to add and doesn't add much value, we can ignore.
