### ISSUE TITLE
Create Recommendations Service Wiki Page

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#46]
We need a wiki page that goes over the business value of the recommendations service and talks about the key tech showcase concepts that it will cover. Please see the [Controller API](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Logistics-Wizard) wiki page for reference.

Story #17

**Comment by shenybluemix** [comment]
Recommendation Service Wiki page is here: 
https://github.com/IBM-Bluemix/logistics-wizard/wiki/Logistics-Wizard-Recommendation-Service
