### ISSUE TITLE
Create Weather Service wiki page

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#47]
We need a wiki page that goes over the business value of the weather analytics service and talks about the key tech showcase concepts that it will cover. Please see the [Controller API](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Logistics-Wizard) wiki page for reference.

_Needs covering story_

**Comment by blumareks** [comment]
https://github.com/IBM-Bluemix/logistics-wizard/wiki/Logistics-Wizard-Weather-Analytics
