### ISSUE TITLE
Determine what objects will be shared

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#48]
Since each user has their own data set for their login creds, we need to determine what objects will be shared between accounts and what objects will be unique.

Story #11

**Comment by l2fprod** [comment]
in the ERP service, Inventory and Shipment would be specific to a demo session. I'm not talking about user, but about demo session. A demo session may involve several Users, as defined in the ERP service. These Users (supply chain manager, retail manager) will see the same session objects (inventory and shipments).  Distribution Centers, Products, Retailers, Suppliers would be the same for all sessions.

**Comment by JakePeyser** [comment]
I agree with this @l2fprod - I think the specifics of what a "session" looks like still needs to be defined more clearly, but this is work for #54 

This info should probably be placed in the wiki

**Comment by JakePeyser** [comment]
After the [conversation with the JDE team](https://ibm.box.com/s/2iu08f0jfhgtxwo66azm328qok9fv74n) last week, we will move forward with this model. There is a chance that we will revise this model when we integrate with the ERP system to include `Orders`, but we will incorporate those changes when needed.

Shared object details laid out in [Data Models wiki page](https://github.com/ibm-bluemix/logistics-wizard/wiki/Data-Model)

**Comment by JakePeyser** [comment]
@l2fprod and @benrondeau, please review

**Comment by l2fprod** [comment]
@JakePeyser: makes sense to me.

**Comment by benrondeau** [comment]
@JakePeyser Looks fine to be.

I also am not well versed in this area of tech, so please take my feedback accordingly and not rely on it heavily :)
