### ISSUE TITLE
Mockups for Map View

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#51]
Need to create the design and UX for how the personas will interact with the basic map. Need to address the following:

- [ ] Map UI
- [ ] How will users interact with distribution centers/retailers?
- [ ] Icons for the map markers

Story #8

**Comment by JakePeyser** [comment]
@benrondeau please flesh this out a bit based on your knowledge of the demo and ask any questions where you still see gaps

**Comment by benrondeau** [comment]
We need to dive deeper into the [scenarios](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Scenarios) and [demo sessions](https://github.com/IBM-Bluemix/logistics-wizard/wiki/Demo-Sessions) so I know what UI elements are needed and how users will interact with them. Currently they are high level and don't give much depth as to how each persona will consume and respond to data they see, as well as what data will be coming their way (specifically).

This is likely going to need Uwe's input as well.

@JakePeyser Based on the above needing to occur, not sure this can be completed in this sprint. Thoughts?

**Comment by JakePeyser** [comment]
Agreed, I moved it out of this sprint a few days ago

**Comment by benrondeau** [comment]
@JakePeyser Will you be available early next week to walk through some demo session flows?

**Comment by JakePeyser** [comment]
Yes @benrondeau let's talk Monday

**Comment by benrondeau** [comment]
Murally Board created of happy path for user: https://app.mural.ly/t/ibm14/m/ibm14/1466611927389.

UI yet to be constructed (working on it).

**Comment by benrondeau** [comment]
@jakepeyser Created [this document](https://ibm.box.com/s/lkxb7ka7mzwgop9mb881izeqzywz5qc9) to outline how ERP data will be exposed to the UI. There are missing data objects listed at the bottom that need to be addressed. Would be nice to walk though this together soon, as building the UI is dependent on it. Thanks

**Comment by colbycheeze** [comment]
Issue moved to [IBM-Bluemix/logistics-wizard-webui #7](https://github.com/IBM-Bluemix/logistics-wizard-webui/issues/7) via [**ZenHub**](https://www.zenhub.com/)
