### ISSUE TITLE
Initial Data Set Creation

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#53]
Create the data set that will be used as the initial distribution centers, retailers, and shipments when users create a new account or revert their data to a fresh state.

**Comment by l2fprod** [comment]
The ERP service has a mechanism in place to inject data into the database:
https://github.com/IBM-Bluemix/logistics-wizard-erp/tree/master/seed

with a set of (unprotected today) routes in https://github.com/IBM-Bluemix/logistics-wizard-erp/blob/master/server/boot/routes-demo.js to init and reset the database.

Part of this mechanism will be used to initialize a demo session.

**Comment by jakepeyser** [comment]
Revisiting this @l2fprod...

We have now defined the static and instance data for demo sessions. I am seeing that there is an initial data set available upon demo creation. Is this item's completion contingent on real data for the ERP system or do you want to make that a separate TODO for a later date?

**Comment by l2fprod** [comment]
This task is to get real data for our scenarios. The initial dataset I put is from the supplychain demo.

**Comment by jakepeyser** [comment]
That's fair, but then I would posit that this task should not be a part of story #8.

**Comment by l2fprod** [comment]
Agreed. Could even be a story on its own actually.
