### ISSUE TITLE
Decide on Service Registration/Discovery Method

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#55]
Need to decide on the service we will use for service discovery and registration

Story #6

**Comment by JakePeyser** [comment]
Everyone ok with moving this out of the current sprint? I think basic connectivity via direct HTTPS communication should suffice for this deliverable.

cc @l2fprod @benrondeau @blumareks @shenybluemix

**Comment by l2fprod** [comment]
@JakePeyser agreed. Service Discovery will add a level of indirection but does not change the core APIs.

**Comment by benrondeau** [comment]
@JakePeyser Dido what @l2fprod says

**Comment by jakepeyser** [comment]
Researching Bluemix [Service Discovery](https://new-console.ng.bluemix.net/docs/services/ServiceDiscovery/index.html) service for this capability

**Comment by rvennam** [comment]
Agree with using the SD service and letting CF handle the instance load balancing.
