### ISSUE TITLE
Scope out CD Work

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#56]
How are we going to institute a continuous delivery model - Deploying all these services, etc. with a single button

IBM Toolchain?

**Comment by JakePeyser** [comment]
Currently creating the template for the Toolchain we will be using

**Comment by JakePeyser** [comment]
Toolchain live at https://new-console.ng.bluemix.net/devops/toolchains/c578fed7-779e-458a-b582-620aa436b899

**Comment by jakepeyser** [comment]
@l2fprod I have done my due diligence on trying to configure coveralls for the IDS pipelines and have concluded that all of the existing packages require the `.git` folder to operate correctly, however IDS seems to omit this when pulling the repo. I can get `python-coveralls` to post results, but it is does not include branch and commit info which defeats much of the usefulness. Need to follow up to see if it is possible to get `.git` to be pulled by IDS...

**Comment by jakepeyser** [comment]
Successfully moved coverage testing into IDS pipelines in commits https://github.com/IBM-Bluemix/logistics-wizard/commit/24c2eeb3b800ed5a316cf341db7606d5d9f97807 and https://github.com/IBM-Bluemix/logistics-wizard-toolchain/commit/393683cb6f307d0e2f3b40e65c631e3b3969c6a5
