### ISSUE TITLE
User Auth for Controller

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#58]
Implement user authentication and authorization in the Controller service

Story #11 (Dependent on #50)

**Comment by JakePeyser** [comment]
I have been debating whether to put the access-control logic within an external database or the controller application logic itself. From my readings, I have gotten seen a quorum that an external DB should enforce constraints. [This StackOverflow post](http://stackoverflow.com/questions/464042/should-you-enforce-constraints-at-the-database-level-as-well-as-the-application#answer-464119) sums it up well. I am now leaning toward this approach, placing `roles` and `permissions` within a relational DB all services can access. I know Loopback implements authorization at the app layer, but I think the implementation can be different for services. Anyone have a strong reason not to take this approach?

cc @l2fprod @benrondeau @blumareks @shenybluemix

**Comment by l2fprod** [comment]
@JakePeyser, not sure I get it - the SO discussion goes in either directions.

For foreign keys, unique, field lengths, using the DB features is straightforward. But do you also want to implement constraints like "only a retailstoremanager can create a new shipment for product X" within a database trigger? (or even more complex business logic - I'm thinking business rules here).

**Comment by JakePeyser** [comment]
My thoughts were along the lines of "retailstoremanager can edit shipments" in a DB to represent high-level permissions, as opposed to hard-coding that logic into the app. However, based on discussion with @l2fprod I am going to remove all auth from controller and place this responsibility entirely on the ERP

**Comment by JakePeyser** [comment]
Refactored to just broker user and auth calls - currently returning dummy data until I get ERP endpoints that will fulfill implementation. Also, generating JWTs that wrap up user info and Loopback token.

@l2fprod two open questions:
1. Are we both enforcing token expiration now? Or will one of these tokens never expire and it is up to the other one to enforce token refresh? I need to update depending on answer to this.
2. This is probably dependent on your `/Demo` implementation (or whatever endpoint you create that fulfills that functionality), but what will you be returning along with the Loopback token when a user logs in? I am curious what I will be wrapping inside the JWT along with it (i.e. user role, id, etc.)

**Comment by l2fprod** [comment]
@JakePeyser 
1. Loopback AccessTokens have a default TTL of 2weeks and expose their creation date as an attribute. When they expire user should login again or get a new token before the current one expires.

2. I pushed a version where /POST Demos return a demo object with a "users" attribute. The POST returns the user passwords as they were created during the POST call. However the /GET Demos/{guid} returns the users without the password. If we want to always show the login/password for the users we will need to store them. The /POST Demos/loginAs allows to get an accessToken for a user attached to the demo session. Then you can also call /GET Users/{id}roles passing the accessToken to retrieve the user roles. Might be missing a /GET Users/{id} (it is there but hidden currently).

**Comment by JakePeyser** [comment]
@l2fprod Follow-up questions:

1. I would rather have the user logged out than for the session to be automatically refreshed. So that I know what it will look like, what code will be returned on an authenticated call when the token is expired?
2. That all LGTM, but I have concerns on two of the calls:
    - `POST Demos` -  What users are created when we make this call? Also, if we do create users, do their passwords need to be returned?
    - `GET Demos/{guid}` - I will need the passwords returned as well if we are to allow them to login without typing their credentials

**Comment by l2fprod** [comment]
@JakePeyser 
1. 401 is returned if token is no longer valid
2.
  * Currently one supply mgr, one store manager. No other API yet to create users
  * To login without credentials, there is POST /Demos/loginAs that takes guid + id. It basically returns an access token for a given user of a given demo session. See the unit tests and http://logistics-wizard-erp.mybluemix.net/#/demo. We will need to store passwords only if we want the business users to type their credentials.

**Comment by JakePeyser** [comment]
1. Sounds good, as long as a message is returned that "Token is no longer valid" or something instead of general unauthorized message
2. 
    - I don't think we should proactively create a store manager since we need to associate them with a location
    - I think that makes the API less realistic. We can avoid using the guid for login altogether if we just use username/password. Then we can demonstrate proper pw hashing on the back end, as well.
