### ISSUE TITLE
Remove regular user signup and methods from ERP API

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#59]
Aim is to remove the default LoopBack API from the existing simulator to only keep those we need in the demo scenario (login/logout)

Story #11 (Dependent on #50)

**Comment by JakePeyser** [comment]
LGTM

**Comment by JakePeyser** [comment]
Curious as to [how other services decrypt `AccessToken` to get user auth](https://github.com/IBM-Bluemix/logistics-wizard-erp/commit/7b9afa501d922b7c22604e0de344f7d85ad45f01#commitcomment-17572679)...is there a hash function we will all be using?

**Comment by l2fprod** [comment]
@JakePeyser https://github.com/IBM-Bluemix/logistics-wizard-erp/commit/7b9afa501d922b7c22604e0de344f7d85ad45f01#commitcomment-17574924
