### ISSUE TITLE
User Auth Testing

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/logistics-wizard#60]
Creation of unit tests, verification, and validation of the auth system

- [x] Controller
- [x] ERP

Story #11 (Dependent on #58, and #59)

**Comment by l2fprod** [comment]
Unit testing for the ERP service is done as part of the respective ERP service tasks (source code for tests under https://github.com/IBM-Bluemix/logistics-wizard-erp/tree/master/test)

**Comment by JakePeyser** [comment]
Postman collection made (check it out in the [README](https://github.com/IBM-Bluemix/logistics-wizard/blob/master/README.md)), need to finish unit tests
