### ISSUE TITLE
Add supplychain and retailstore manager roles in ERP

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#61]
related to #11

**Comment by l2fprod** [comment]
added as part of https://github.com/IBM-Bluemix/logistics-wizard-erp/commit/f78f0f4f3e32a4abfb5b0d98a165972ab7230609  supplychain and retail have READ on all. supplychain has WRITE on shipments.

**Comment by JakePeyser** [comment]
Aside from [note about giving `retailstoremanager` WRITE permission on shipments](https://github.com/IBM-Bluemix/logistics-wizard-erp/commit/f78f0f4f3e32a4abfb5b0d98a165972ab7230609#commitcomment-17572575), LGTM
