### ISSUE TITLE
Write Controller Methods for Retrieving ERP Data

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#62]
Write API methods in the controller for retrieving and returning basic ERP data

Story #8

**Comment by jakepeyser** [comment]
After discussing admin and map views with @benrondeau, we will need the following methods: 
- create shipment
- view shipments
- view shipment (shipment ID)
- view retailers
- view distribution centers
- load admin view (all data retrieval necessary for initial rendering)
- view sales data (retailer ID)

**Comment by jakepeyser** [comment]
[Controller Swagger doc](https://github.com/IBM-Bluemix/logistics-wizard/blob/3f691697dbae46444dd0d10f8b796929ca90f534/swagger.yaml) updated to reflect upcoming changes to API for methods around retrieving and creating ERP data
FYI @benrondeau

**Comment by jakepeyser** [comment]
API methods and test created:
- [ ] `GET /shipments`
- [ ] `GET /shipments/<id>`
- [ ] `DELETE /shipments/<id>`
- [ ] `PUT /shipments/<id>`
- [ ] `GET /distribution-centers`
- [ ] `GET /distribution-centers/<id>`
- [ ] `GET /retailers`
- [ ] `GET /retailers/<id>`
- [ ] `GET /retailers/<id>/shipments`
- [ ] `POST /retailers/<id>/shipments`
- [ ] `GET /retailers/<id>/sales`
- [ ] `GET /products`

**Comment by jakepeyser** [comment]
@benrondeau FYI I changed the call to create a shipment to `POST /shipments` bc it makes more sense semantically and avoids duplicate inputs. It is reflected in this issue and the [swagger doc](https://github.com/IBM-Bluemix/logistics-wizard/blob/master/swagger.yaml)

**Comment by jakepeyser** [comment]
Removed `GET /retailers/<id>/sales` from checklist as it is not yet needed and does not align with story #8

**Comment by benrondeau** [comment]
I ran into some issues with testing the API with postman. I created a demo successfully, used the `GUID` to get list of retailers, but got a `404` "Demo or retailer does not exist" error on the `GET` call for `demo/guid/users` and

**Comment by jakepeyser** [comment]
@benrondeau The correct URL is `/demos/guid/users`, but I'll assume that's a typo. Make sure that you are making a POST request for that call and not a GET and also make sure you have `{{demo_id}}` set in the body of the request. Just checked and it is working for me. Do the same thing for the `demos/guid/login` call with the `userId` value in the body

Currently, all DELETE calls return a `204` on success as described in the spec. The research (like [this Quora answer](https://www.quora.com/What-is-the-appropriate-HTTP-response-code-to-a-successful-DELETE-request) for example) I have done seems to conclude an empty response if we have nothing to tell the client upon success, which seems to be the case on our deletes. If people think otherwise we can change that behavior across the board.

I use [Postman environments](https://www.getpostman.com/docs/environments) to streamline changing calls between local/test/prod. I still need to figure out a way to include those with the Get Postman button (if it is possible w/o a paid account) and will update the button if I figure that out. Meanwhile, here is what my prod setup looks like, for instance:
![image](https://cloud.githubusercontent.com/assets/1534503/16510766/93cb41b6-3f0e-11e6-9318-c5cdce6c53d7.png)

**Comment by jakepeyser** [comment]
@benrondeau FYI the Postman collection now comes preconfigured with an environment that has the referenced `{{vars}}`

**Comment by benrondeau** [comment]
Nice. Thanks for doing that

**Comment by jakepeyser** [comment]
Has anyone fully tested this? Been in review status for >1 week
