### ISSUE TITLE
New Demo API to create/find a demo and login as one of the user

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#66]
POST /Demo
-> create a new env

GET /Demo/findByGuid/{guid}
-> retrieve users

POST /Demo/loginAs guid and userId 
-> get a token for this user

related to #11

**Comment by JakePeyser** [comment]
LGTM as far as the description of this issue goes, although it doesn't quite match the title. However, I think other issues cover this as well
