### ISSUE TITLE
Ensure Swagger API correctly describe the "Demo" entity

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#68]
Currently in the Swagger demo is
`{ id, createdAt, email }`

but the create and findByGuid API actually return the users attached to the Demo environment as an additional attributes. This is not explicit in the Loopback model but only done on the fly by the code in demo.js. We should a way to have it visible in the Loopback model and then in the Swagger. If that's not possible then at least update the spec.yml.

related to #11

**Comment by JakePeyser** [comment]
At least add it to `spec.yml` for now so callers know what they are getting. Updating the Loopback model would be nice to have, but not necessary

**Comment by JakePeyser** [comment]
As [noted here](https://github.com/IBM-Bluemix/logistics-wizard-erp/commit/64bb13424cdde2b5194ccd61ad1edb45de8979da#commitcomment-17680184), this still needs to be addressed

**Comment by l2fprod** [comment]
demo > users > roles now showing in the spec.yaml:

![image](https://cloud.githubusercontent.com/assets/12746550/16037348/593f7e54-3220-11e6-9df3-9a48ed08b4c4.png)

I can't find a simple way to have this in the loopback too - unless creating a new "fake" model for the response.

**Comment by JakePeyser** [comment]
> I can't find a simple way to have this in the loopback too

What does this mean exactly? You can't get it to auto-generate when you recreate the model?

**Comment by l2fprod** [comment]
Yes. Sounds like the solution is to create this fake model like I did for the "LoginResponse" for loginAs but I find this a bit overkill.

**Comment by JakePeyser** [comment]
What if you just add an array of `Role` objects into the `ERPUser` object as an optional parameter, instead of using `ERPUserWithRoles`. I think the fact that it is at least there is more important on a definitive "It will be in this particular response" in [`spec.yml`](https://github.com/IBM-Bluemix/logistics-wizard-erp/blob/master/spec.yaml)

**Comment by JakePeyser** [comment]
LGTM
