### ISSUE TITLE
New API to add a retail store manager to a Demo session

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#69]
so that you can run a demo scenario with multiple stores

POST /Demos/{guid}/createUser

**Comment by JakePeyser** [comment]
@l2fprod this is covered by #98, right?

**Comment by l2fprod** [comment]
@JakePeyser I'm not a big fan of the checklist in task. It makes it more difficult to track what we need to do. I find one task, one assignee better. If something needs to cross modules, we create several tasks and attach them to a story.

**Comment by JakePeyser** [comment]
@l2fprod I agree with your point on splitting them into separate tasks. We will make sure to do that next sprint

**Comment by JakePeyser** [comment]
Tested and LGTM
