### ISSUE TITLE
New API to assign a Retail Store manager to a store

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#70]
This might only be needed when create a Retail Store manager and not be an API but rather a parameter when creating the store manager

related to #11

**Comment by JakePeyser** [comment]
Agreed, this should just be a parameter on the endpoint created for #69

**Comment by JakePeyser** [comment]
@l2fprod this is also covered by #98, right?

**Comment by JakePeyser** [comment]
I am calling `POST Demos/{{guid}}/createUser` with `retailerId` in the payload and am getting a 400 error with a response message of "retailerId is a required arg". I think it is b/c the ID I am using is invalid, so two things:
- Can we get a more descriptive message when an invalid `retailerId` is used?
- Can you give me a valid ID with which to test?

**Comment by JakePeyser** [comment]
I am getting a `404` when hitting the `POST Demos/{{guid}}/createUser` API

**Comment by JakePeyser** [comment]
Works for me, but two things:
- Should we be allowed to overwrite the current retail store manager using this method? Right now, it just allows it.
- This proves we need to bring out Retailers (or their child Contact) into the shared data pool. I'm not sure of the scope of this for you @l2fprod, is this something that can be done easily or must we push it to the next sprint?

**Comment by JakePeyser** [comment]
Popping this back up for review @l2fprod. Second issue above is covered, but still curious what you think about the first one:
> Should we be allowed to overwrite the current retail store manager using this method? Right now, it just allows it.

**Comment by l2fprod** [comment]
@JakePeyser: indeed, makes sense to prevent that. We can always add an "update storage manager" API later on if needed.

**Comment by JakePeyser** [comment]
Tested and LGTM. I'd say this issue is complete
