### ISSUE TITLE
New API to delete a Demo environment

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#71]
DELETE /Demos/{guid}
to delete all users and their related data

related to #11

**Comment by JakePeyser** [comment]
I'm hitting the endpoint `Demos/deleteByGuid/{{guid}}` and getting a 404. Is this the wrong endpoint?

**Comment by l2fprod** [comment]
it is DELETE /Demos/{guid} (I've updated the spec.yaml)

**Comment by JakePeyser** [comment]
Thank you, tested, and LGTM
