### ISSUE TITLE
Reserve URL for App

### ISSUE THREAD

**Issue by benrondeau** [IBM-Bluemix/logistics-wizard#72]
Noticed that the URL `logistics-wizard.mybluemix.net` was not registered so I created an app under the 'dev-advocates' org in Bluemix in the 'demos' space. It is just a placeholder app to hold our desired URL.

http://logistics-wizard.mybluemix.net/

**Comment by JakePeyser** [comment]
thanks Ben, haven't deployed it to Bluemix yet so I'll use that app
