### ISSUE TITLE
App Can Used Without Any Setup/Coding/Development

### ISSUE THREAD

**Issue by benrondeau** [IBM-Bluemix/logistics-wizard#75]
**Success looks like:**
App can be run by non-technical person, such as a tech seller in front of a client or a quick demo at a trade show. This can be accomplished by having an example version of the app running on Bluemix that a user can click on to use the app without setting up a Bluemix account, coding something, or the like.

**Failure looks like:**
App requires a Bluemix account, 15 setup steps, in-depth coding knowledge, installing binaries on their machine or similar hoops to jump through just to experience the app.

**Comment by benrondeau** [comment]
Already in the works by @jakepeyser via 'Deploy to Bluemix' button and Toolchain option

**Comment by jakepeyser** [comment]
There will have to be _some_ manual work done to set certain components up (i.e. real-time messaging) as they cannot be integrated into the Toolchain. However, I am looking to minimize these, as we all should.

**Comment by l2fprod** [comment]
@jakepeyser: the ERP service database initialization is this kind of one-off task that needs to be done. With Postgres and Loopback, we will need to create the tables outside of the ERP service. I don't know how it can be integrated into the toolchain? Is there some place where we can run scripts only once (like creating the Bluemix services as examples).

**Comment by jakepeyser** [comment]
@l2fprod As we consider this problem, it's important to keep [admin processes for a 12-factor app](http://12factor.net/admin-processes) in mind

So we can do this in two ways as I see it:
- In the Toolchain, we can create jobs in the BUILD or DEPLOY stage that do them for us. We already use the DEPLOY stage to create CF services. However, this means that they would not be repeatable and thus cannot be used for admin tasks needed outside the startup process
- We can have a Redis queue (or something similar) that handles one-off tasks and can be handled by an instance of the app that pulls the job

**Comment by benrondeau** [comment]
FYI - the purpose of this standard was to avoid long 14 step processes to deploy an app. If it requires a couple steps, especially for an app of this complexity, than that's totally acceptable
