### ISSUE TITLE
User Can Find Help & Report Bugs

### ISSUE THREAD

**Issue by benrondeau** [IBM-Bluemix/logistics-wizard#76]
**Success looks like:**

1) README has a clear instructions on how to report bugs/issues (such as the Github issue tracker).

2) How to get help during the business day if the app is not working (an email address, slack group, etc.). 

**Failure looks like:**
- User has no idea how to report bugs in the app, so they are not reported and can go unnoticed by our team for weeks or months
- A user (such as an IBMer) need to show the app to a customer but the app is not working (maybe because a service name changed that the app uses) and they have no idea how to get help.

**Comment by benrondeau** [comment]
Item 1 is good. Thoughts about item 2 @jakepeyser and @l2fprod?

**Comment by jakepeyser** [comment]
That is a good question. We could open up a `#logistics-wizard-support` channel in Slack, but this limits participants to people in CloudPlatform. Two other potential options:
- Include a mechanism for submitting issues directly in the app, perhaps the footer
- I am currently setting up a Gmail account to handle the demo creation emails. Maybe we can direct people to this email and have the account forward all incoming emails to our work addresses?

**Comment by l2fprod** [comment]
We should start with directing people to Github issues and not create another channel of support.

**Comment by benrondeau** [comment]
Will we actually respond to Github issues in the same business day?

The purpose of this standard is that an IBMer showing a demo has a direct line of communication to the right person if they have a problem, especially in situations when they are in front of a client.

One option would be [Gitter](https://gitter.im), as you can setup email alerts when someone posts in the channel and the chat room is public so other people can see other problems/solutions.
