### ISSUE TITLE
Proper Error Feedback in App's UI & Dev Console

### ISSUE THREAD

**Issue by benrondeau** [IBM-Bluemix/logistics-wizard#77]
**Success looks like:**
In the event the application fails, such as a form fails to submit or to connect to a back-end database, the application's UI alerts user to the error and description of what happened(i.e. 'Error - can't connect to database'). Relevant error output is also available in the dev console so it can be diagnosed/fixed by the developer.

**Failure looks like:**
The application fails silently or generically (i.e. no message or a generic 'error'), leaving the user clueless as to what happened and where to start looking to diagnose/fix the error.

**Comment by benrondeau** [comment]
@l2fprod and @jakepeyser - I assume error output is being included in the development of the back-end code?

**Comment by jakepeyser** [comment]
Yes, the ERP passes back errors and controller propagates them to the user. The `Error` object is defined in the swagger spec

**Comment by benrondeau** [comment]
Nice. I will work on the front end to ensure this is taken advantage of.
