### ISSUE TITLE
Application Credentials Accessible to Team

### ISSUE THREAD

**Issue by benrondeau** [IBM-Bluemix/logistics-wizard#89]
**Success looks like:**
Application credentials (such as for accessing services) are accessible to the entire dev advocate team so that changes can be made as necessary by team members.

They can be stored in app's environment variables, a separate credentials file or any other way that keeps them secure yet available to the team.

**Failure looks like:**
App credentials are kept secret and when the app's developer is out of touch on vacation, a service stops working and the team cannot access/troubleshoot the issue.

**Comment by jakepeyser** [comment]
[Email account credentials Box note](https://ibm.box.com/s/ecmkcq30a3r1g0wnviuw93aq8015rys1)
