### ISSUE TITLE
Create Design Style Guide for App

### ISSUE THREAD

**Issue by benrondeau** [IBM-Bluemix/logistics-wizard#92]
Create the visual and experience style guide for our app, extending the IBM Design Language (extension of issue #81) .

**Comment by benrondeau** [comment]
Logo for app included in this task.

**Comment by colbycheeze** [comment]
@kingtraceyj Do you have a color palette in mind yet?
Here are some default variables we have set up in our project (came from material-ui) so you can use this as a reference for coming up with ideas.

You can customize this palette and add/remove anything that suits our project so this is just what exists now if you look through the material-ui docs and see the various colors.
```
palette: {
    primary1Color: cyan500,
    primary2Color: cyan700,
    primary3Color: grey400,
    accent1Color: pinkA200,
    accent2Color: grey100,
    accent3Color: grey500,
    textColor: darkBlack,
    alternateTextColor: white,
    canvasColor: white,
    borderColor: grey300,
    disabledColor: fade(darkBlack, 0.3),
    pickerHeaderColor: cyan500,
    clockCircleColor: fade(darkBlack, 0.07),
    shadowColor: fullBlack,
  },
```

**Comment by kingtraceyj** [comment]
great. i do have a basic color palette and am going to work on some accent colors. i take a look at the attributes and get those to next week.

**Comment by kingtraceyj** [comment]
@colbycheeze & @LRRoberts0122 

Here's what I have so far. more colors coming soon! let me know if you need something else thats not listed so far.

primary1Color: #0F94A7,
primary2Color: #485566,
accent1Color: #91C383,
textColor: #485566,
alternateTextColor: #FFFFFF,
canvasColor: #EFF2F5,
borderColor:  #DADDE0,

![lw_color](https://cloud.githubusercontent.com/assets/20582179/17713862/b377bf84-63c2-11e6-9543-29ee913c40ba.png)

**Comment by colbycheeze** [comment]
Issue moved to [IBM-Bluemix/logistics-wizard-webui #8](https://github.com/IBM-Bluemix/logistics-wizard-webui/issues/8) via [**ZenHub**](https://www.zenhub.com/)
