### ISSUE TITLE
Save "name" and "email" for Demo creation

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#93]
In the ERP `POST /Demos` API we need to allow sending of the following data

- demo session name (req)
- email (optional)

The UI will need to ask for these pieces of info and mention that the collection of email is for emailing them their unique demo session IDs for session retrieval.

related to #11 
[Related Notes](https://ibm.box.com/s/jue0czes0g5x9lezki61n1vcfzwi7cbf)

**Comment by JakePeyser** [comment]
I'd like to include the necessary UI design/first development with this issue, so moving back to In Progress and assigning to @benrondeau

**Comment by benrondeau** [comment]
@JakePeyser I assume this will only apply to the 'start new session' flow?

And how will a user continue a previous session? That is not reflected Murally board.

**Comment by JakePeyser** [comment]
You are correct. During [today's meeting](https://ibm.box.com/s/jue0czes0g5x9lezki61n1vcfzwi7cbf) we decided that they will only be able to continue a previous session by hitting the unique demo session login page directly - whether via bookmark or link from the email we send. I will update Mural.ly for you

**Comment by benrondeau** [comment]
Prototype updated to capture name/email during session creation flow: https://invis.io/3A7LILC5Y

**Comment by benrondeau** [comment]
Assuming this has been completed?

**Comment by jakepeyser** [comment]
Yes, as long as there exists a front end task for this work

**Comment by benrondeau** [comment]
Yep. That is part of the UI design already. I will close the issue.
