### ISSUE TITLE
Send email upon Demo creation and do not store value

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#94]
Remove `email` parameter from Demo object used by the ERP service. Instead, the Controller will send email with the demo session unique ID if the user included their email in the demo creation step.

related to #11 
[Related Notes](https://ibm.box.com/s/jue0czes0g5x9lezki61n1vcfzwi7cbf)

**Comment by JakePeyser** [comment]
I'd like to include changes to the Controller in this issue as well, so moving back to In Progress and assigning to myself

**Comment by jakepeyser** [comment]
Compiled notes containing [email accounts and SMTP server details](https://ibm.box.com/s/ecmkcq30a3r1g0wnviuw93aq8015rys1)

**Comment by jakepeyser** [comment]
Initial email template for welcome email:
```
Congratulations, you have created a new session for the Logistics Wizard demo! You can access your demo session at the following URL:
https://logistics-wizard.mybluemix.net/demo/JDJhJDEwJFRzVmkuZDJJQTNrcTNUcnd5MjdCY3VNRFJrcGRLOERiemJlL1BVT2lsMmkxVjEzUEJOa0dh

If you want to take the demo beyond the UI, you may find the following information useful:

GUID: JDJhJDEwJFRzVmkuZDJJQTNrcTNUcnd5MjdCY3VNRFJrcGRLOERiemJlL1BVT2lsMmkxVjEzUEJOa0dh
Default Username: Supply Chain Manager (XFqyhSTM7l)
Default User ID: d83dfd4a85464ad5b5532bf2fad3ed2f
The Logistics Wizard Controller API is entirely open so that anyone is able to leverage it programmatically or create their own UI. Check out the Swagger API Spec to better understand the methods available to you or take advantage of our Postman collection to help you get started with the REST interface.

Thanks,
The Logistics Wizard Team
```

We can improve this as we implement the front end, but let me know if anything vital is missing.

**Comment by jakepeyser** [comment]
Removed email send during demo creation until one-off tasks are possible - https://github.com/IBM-Bluemix/logistics-wizard/commit/dad21f4c315b2ea4ef9c3c5e4cd0e38300084baf

**Comment by jakepeyser** [comment]
@l2fprod I moved welcome email to [`/emails/welcome.html`](https://github.com/IBM-Bluemix/logistics-wizard/blob/master/server/emails/welcome.html) and made interfacing code in [`messaging.py`](https://github.com/IBM-Bluemix/logistics-wizard/blob/master/server/services/messaging.py#L8-L17) extensible to handle future emails. We use the Python notation for formatting (i.e. `{num}`) to handle dynamic inputs in the HTML templates.

**Comment by l2fprod** [comment]
LGTM
