### ISSUE TITLE
Remove /Users/login, replaced with /Demos/loginAs

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#96]
Not needed, as no more passwords since `guid`/`user_id` combo will be used as login credentials.

related to #11 
[Related Notes](https://ibm.box.com/s/jue0czes0g5x9lezki61n1vcfzwi7cbf)

**Comment by JakePeyser** [comment]
@l2fprod can you update your [spec.yml](https://github.com/IBM-Bluemix/logistics-wizard-erp/blob/master/spec.yaml) file? It is easier for me to develop to that than look through the models

**Comment by JakePeyser** [comment]
Is there an API for retrieving a single user using a demo guid and user ID? This would be useful instead of retrieving the demo and then looking through the list of users

**Comment by JakePeyser** [comment]
The solution to this issue LGTM

**Comment by l2fprod** [comment]
@JakePeyser: no API to retrieve a single user. Do we have an immediate use?

**Comment by JakePeyser** [comment]
@l2fprod yes, when a user logs in we need to wrap their User object in the JWT with the loopback token id. Right now, the only way to do that would be to retrieve the full demo object and pick the user out of the list.

The other option would be to return the User object on the 'loginAs' call

**Comment by JakePeyser** [comment]
I am going to work around this for this release, but here is my formal request for this method in next sprint 😃
