### ISSUE TITLE
Ability for client to retrieve list of retail locations for retail manager creation

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#97]
#Add new `GET /Demos/{guid}/retailers` API that exposes retail locations, isManager boolean, and the manager name (if any) and use it to expose to users during new retail manager creation.

This issue includes the following tasks:
- [x] make ERP API changes
- [x] make controller API changes

related to #11 
[Related Notes](https://ibm.box.com/s/jue0czes0g5x9lezki61n1vcfzwi7cbf)

**Comment by l2fprod** [comment]
@JakePeyser if we need to create a link between ERPUser and Retailer, we might need to revisit our conclusion about having only Inventory and Shipment being "per demo session". Retailers might need to be included in this list too.

**Comment by JakePeyser** [comment]
I agree @l2fprod, at the very least the Retailer.Contact object must be unique

**Comment by JakePeyser** [comment]
@benrondeau Controller and ERP APIs are completed, check out their swagger docs for API specs

**Comment by jakepeyser** [comment]
Moved UI task to #137
