### ISSUE TITLE
Ability to create a new ERPUser and add them to a demo session

### ISSUE THREAD

**Issue by l2fprod** [IBM-Bluemix/logistics-wizard#98]
We need the ability for the user to create a new retail store manager and assign them to an open retail location.

This issue includes the following tasks:
- [x] Add a new `POST /Demos/{guid}/createUser` API to handle creating new user
- [x] Replace `contact` in retailer with ERPUser.
- [x] New Controller API to handle request routing

related to #11 
[Related Notes](https://ibm.box.com/s/jue0czes0g5x9lezki61n1vcfzwi7cbf)

**Comment by JakePeyser** [comment]
@benrondeau Controller and ERP APIs are completed, check out the swagger files for API specs

**Comment by jakepeyser** [comment]
Moved UI task to #136
